services:
  web:
    image: nginx
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src/public:/var/www/html/src/public
    ports:
      - "81:8080" # Убедитесь, что Nginx слушает порт 8080
    restart: always
    depends_on:
      - php-fpm
      - database

  php-fpm:
    build: ./docker
    restart: always
    volumes:
      - ./docker/php/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-debug.ini
      - ./src/public:/var/www/html/src/public
    env_file:
      - .env

  database:
    image: postgres:latest
    restart: always
    ports:
      - "54321:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
